included:
  - Sources
  - Tests

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_length
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - multiline_parameters

identifier_name:
  min_length:
    error: 3
  excluded:
    - id

line_length: 160

type_name:
  min_length: 3
  max_length:
    warning: 30
    error: 40
