os:
  - osx
language: generic
osx_image:  xcode10
notifications:
  email:
    on_success: never
    on_failure: never
jobs:
    include:
        - stage: swiftpm10
          name: "Swift Package Manager build"
          script: swift build
        - stage: xcode10
          name: "Xcode build"
          script: xcodebuild -scheme MastodonKit-macOS build
        - stage: xcode10unit
          name: "Unit Tests"
          script: xcodebuild -scheme MastodonKit-macOS -enableCodeCoverage YES build test
          script: bash <(curl -s https://codecov.io/bash) -cF ios
