os:
  - osx
language: generic
osx_image:  xcode10
notifications:
  email:
    on_success: never
    on_failure: never
jobs:
    include:
        - stage: lint
          name: "SwiftLint"
          script: swiftlint lint
          before_install:
            - brew update && if brew outdated --quiet | grep -qx swiftlint; then brew upgrade swiftlint; fi
        - stage: swift
          name: "Swift Package Manager"
          script: swift test
        - stage: xcode
          name: "Xcode"
          script: xcodebuild -scheme MastodonKit-macOS -enableCodeCoverage YES build test
          after_success:
            - bash <(curl -s https://codecov.io/bash) -cF ios
